version: '3.2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: server-dev
    ports:
      - 8181:8181
    environment:
      SECRETS_ENV: "/usr/src/klendathu/secrets/.env"
    volumes:
      - type: volume
        source: .
        target: /usr/src/klendathu
      - type: tmpfs
        target: /usr/tmp/uploads
