version: '3.2'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client
    ports:
      - 8180:80
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - 8181:8181
    environment:
      SERVER_PORT: 8181
      DEEPSTREAM_URL: "ws://deepstream:6020"
      RETHINKDB_URL: "rethinkdb://db:28015"
      IMGPROC_URL: http://imaginary:9000
      UPLOADS_DIR: /usr/tmp/uploads
      NODE_ENV: development
      DB_NAME: klendathu
      LOG_LEVEL: debug
      SECRETS_ENV: /usr/src/klendathu/secrets/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server/api/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - db
      - deepstream
      - imaginary
    volumes:
      # - type: volume
      #   source: .
      #   target: /usr/src/klendathu
      - type: tmpfs
        target: /usr/tmp/uploads
  deepstream:
    image: deepstreamio/deepstream.io:latest
    container_name: deepstream
    ports:
      - 6020:6020
    volumes:
      - type: volume
        source: ./packages/klendathu-deepstream
        target: /etc/deepstream
    healthcheck:
      test: ["CMD", "curl", "-f", "http://deepstream/health-check"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  imaginary:
    image: h2non/imaginary:latest
    container_name: imgproc
    environment:
       PORT: 9000
    command: -enable-url-source
    ports:
      - "9000:9000"
  db:
    image: rethinkdb:2.3.6
    container_name: rethinkdb
    ports:
      - 8080:8080   # Admin
      - 28015:28015 # Driver
      - 29015:29015 # Cluster
    volumes:
      - type: volume
        source: ./data
        target: /data
