export enum Predicate {
  // String predicates
  IN = 'IN',
  EQUALS = 'EQUALS',
  NOT_IN = 'NOT_IN',
  NOT_EQUALS = 'NOT_EQUALS',
  MATCH = 'MATCH',
  NOT_MATCH = 'NOT_MATCH',
  STARTS_WITH = 'STARTS_WITH',
  ENDS_WITH = 'ENDS_WITH',
  GREATER = 'GREATER',
  GREATER_EQUAL = 'GREATER_EQUAL',
  LESS = 'LESS',
  LESS_EQUAL = 'LESS_EQUAL',
}
