export enum Predicate {
  // String predicates
  IN = 'IN',
  CONTAINS = 'CONTAINS',
  EQUALS = 'EQUALS',
  MATCH = 'MATCH',
  NOT_IN = 'NOT_IN',
  NOT_CONTAINS = 'NOT_CONTAINS',
  NOT_EQUALS = 'NOT_EQUALS',
  NOT_MATCH = 'NOT_MATCH',
  STARTS_WITH = 'STARTS_WITH',
  ENDS_WITH = 'ENDS_WITH',
  GREATER = 'GREATER',
  GREATER_EQUAL = 'GREATER_EQUAL',
  LESS = 'LESS',
  LESS_EQUAL = 'LESS_EQUAL',
  HAS_ANY = 'HAS_ANY',
  HAS_ALL = 'HAS_ALL',
}
